### Creation of arrays in Numpy

In [5]:
import numpy as ujwal

def create_arrays():
    # Create a 1D array from a list
    lis = [1, 23, 4, 5, 6, 7, 8]
    ar = ujwal.array(lis)
    print("Array from list:", ar)

    # Create an array with 10 zeros
    arr = ujwal.zeros(10)
    print("Array of zeros:", arr)

    # Create an array with 10 ones
    ones_array = ujwal.ones(10)
    print("Array of ones:", ones_array)

    # Create a filled array of shape (4,) with the value 5
    filled_array = ujwal.full((4), 5)
    print("Filled array:", filled_array)

    # Create a 2D array of zeros with shape (2, 3)
    array_2d = ujwal.zeros((2, 3))
    print("2D array of zeros:", array_2d)

    # Create arrays using arange function
    first = ujwal.arange(0, 5, 1)
    print("First array with range:", first)

    sec = ujwal.arange(1, 8, 2)
    print("Second array with range:", sec)

    thi = ujwal.arange(-7, 2, 2)
    print("Third array with range:", thi)

    fou = ujwal.arange(0.4, 1, 0.15)
    print("Fourth array with range:", fou)

if __name__ == "__main__":
    create_arrays()


Array from list: [ 1 23  4  5  6  7  8]
Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Filled array: [5 5 5 5]
2D array of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
First array with range: [0 1 2 3 4]
Second array with range: [1 3 5 7]
Third array with range: [-7 -5 -3 -1  1]
Fourth array with range: [0.4  0.55 0.7  0.85]


### generating arrays with random values 

In [6]:
import numpy as ujwal

def random_arrays():
    # Generate a random array of integers between 0 and 100 of size 10
    random_array = ujwal.random.randint(0, 101, size=10)
    print("Random array:", random_array)

    # Sort the random array
    sorted_array = ujwal.sort(random_array)
    print("Sorted random array:", sorted_array)

    # Generate another random array using linspace
    linspace_array = ujwal.linspace(1, 10, 7)
    print("Linspace array:", linspace_array)

    # Generate a 3D random array
    random_3d_array = ujwal.random.rand(2, 2, 2)
    print("3D random array:", random_3d_array)

if __name__ == "__main__":
    random_arrays()


Random array: [96 57 92 45 21 98 28 52 24 88]
Sorted random array: [21 24 28 45 52 57 88 92 96 98]
Linspace array: [ 1.   2.5  4.   5.5  7.   8.5 10. ]
3D random array: [[[0.51904869 0.22974532]
  [0.57799907 0.92446583]]

 [[0.18991844 0.5328581 ]
  [0.31135427 0.4732941 ]]]


### Properties of the array

In [7]:
import numpy as ujwal

def array_properties():
    # Generate a random 3D array for property checks
    array_example = ujwal.random.rand(2, 2, 2)
    
    # Print array properties
    print("Number of dimensions:", array_example.ndim)
    print("Size of the array:", array_example.size)
    print("Data type of the array:", array_example.dtype)
    print("Shape of the array:", array_example.shape)
    print("Size of each item:", array_example.itemsize)
    
    # Transpose the array and print
    transposed_array = array_example.transpose()
    print("Transposed array:", transposed_array)

if __name__ == "__main__":
    array_properties()


Number of dimensions: 3
Size of the array: 8
Data type of the array: float64
Shape of the array: (2, 2, 2)
Size of each item: 8
Transposed array: [[[0.79951545 0.75874557]
  [0.7381995  0.90337675]]

 [[0.7252966  0.50326437]
  [0.10101793 0.84622239]]]


### Manipulating arrays,slicing and copying

In [1]:
import numpy as ujwal

def array_manipulation():
    # Create a 1D array
    first = ujwal.arange(0, 5, 1)
    
    # Iterate over the array using niter
    print("Iterating over array using nditer:")
    for x in ujwal.nditer(first):
        print(x)

    # Create a random array and sort it
    random_array = ujwal.random.randint(0, 101, size=10)
    print("Random array:", random_array)

    sorted_array = ujwal.sort(random_array)
    print("Sorted random array:", sorted_array)

    # Original word lists for lexical sorting
    word = ["elderberry", "apple", "banana", "cherry", "date"]
    word2 = ["honeydew", "fig", "grape", "kiwi", "lemon"]
    
    # Convert lists to NumPy arrays
    word_array = ujwal.array(word)
    word2_array = ujwal.array(word2)

    # Lexically sort the arrays using lexsort
    sorted_indices_word = ujwal.lexsort([word_array])
    sorted_indices_word2 = ujwal.lexsort([word2_array])

    sorted_word = word_array[sorted_indices_word]
    sorted_word2 = word2_array[sorted_indices_word2]

    print("Sorted word array:", sorted_word)
    print("Sorted word2 array:", sorted_word2)

    # Generate a random array for median calculation
    random_for_median = ujwal.random.randint(0, 101, size=10)
    median_value = ujwal.median(random_for_median)
    print("Median of random array:", median_value)

    # Create a random 3x3 array for demonstration
    ranarr = ujwal.random.randint(1, 100, size=(3, 3))
    print("Random 3x3 array:", ranarr)

if __name__ == "__main__":
    array_manipulation()


Iterating over array using nditer:
0
1
2
3
4
Random array: [98 81 61 35  4 32 22 87 94  4]
Sorted random array: [ 4  4 22 32 35 61 81 87 94 98]
Sorted word array: ['apple' 'banana' 'cherry' 'date' 'elderberry']
Sorted word2 array: ['fig' 'grape' 'honeydew' 'kiwi' 'lemon']
Median of random array: 53.0
Random 3x3 array: [[35  5 14]
 [78 14 53]
 [10 37  6]]


### element wise addition in numpy 

In [11]:
import numpy as ujwal

def elementwise_operations():
    # Create two 1D arrays for element-wise addition
    array1 = ujwal.array([1, 2, 3])
    array2 = ujwal.array([[1], [2], [3]])

    # Element-wise addition
    summed = array1 + array2

    # Print the result
    print("Summed array:")
    for x in summed:
        print(x)

if __name__ == "__main__":
    elementwise_operations()


Summed array:
[2 3 4]
[3 4 5]
[4 5 6]


### Array Broadcasting

In [13]:
import numpy as ujwal

def elementwise_operations():
    # Create two 1D arrays for element-wise addition
    array1 = ujwal.array([1, 2, 3])
    array2 = ujwal.array([[1], [2], [3]])  # 2D array with shape (3, 1)

    # Element-wise addition
    summed = array1 + array2

    # Print the result of element-wise addition
    print("Summed array (element-wise addition):")
    for x in summed:
        print(x)

    # Example of array broadcasting
    scalar_value = 10
    broadcasted_result = array1 + scalar_value  # Adding a scalar to the 1D array

    # Print the result of broadcasting
    print("Result of broadcasting (adding scalar to array):", broadcasted_result)

if __name__ == "__main__":
    elementwise_operations()


Summed array (element-wise addition):
[2 3 4]
[3 4 5]
[4 5 6]
Result of broadcasting (adding scalar to array): [11 12 13]
