In [1]:
import numpy as ujwal
lis=[1,23,4,5,6,7,8]
l=[1,2,4,5,6,7,8]
ins=[1,3,4,5,6,7,8]
ls=[1,0,4,5,6,7,8]
ar=ujwal.array(lis)
print(ar)
print(type(ar))

[ 1 23  4  5  6  7  8]
<class 'numpy.ndarray'>


In [3]:
#create an array with 10 zeros
arr=ujwal.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
#create an array with 10 ones
thisa=ujwal.ones(10)
print(thisa)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#creating an array with custom values that is filled
ar3=ujwal.full((4),5)
print(ar3)

[5 5 5 5]


In [6]:
#array with range
first=ujwal.arange(0,5,1)
print(first)
sec=ujwal.arange(1,8,2)
print(sec)
thi=ujwal.arange(-7,2,2)
print(thi)
fou=ujwal.arange(0.4,1,0.15)
print(fou)

[0 1 2 3 4]
[1 3 5 7]
[-7 -5 -3 -1  1]
[0.4  0.55 0.7  0.85]


In [7]:
#creating an array of random numbers
a4=ujwal.random.rand(9)*5
print(a4)


[4.30327434 1.5661954  3.57886518 0.45725074 1.52576629 0.72155775
 0.88253618 2.95794939 0.48287472]


In [8]:
# creating an array with the same difference between elements
a5=ujwal.linspace(1,10,7)
print(a5)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [9]:
#creating a 2d array manually
a6=array1 = ujwal.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a6)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#creating a 2d array full of 0s
a7=ujwal.zeros((2, 3))
print(a7)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#creating a 3d array full of 0
import numpy as ujwal
a8=ujwal.zeros((6,3,3))
print(a8)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [13]:
a9=ujwal.full((5,5),9)
print(a9)

a10 = ujwal.random.rand(2, 2, 2)
print(a10)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
[[[0.623986   0.12896306]
  [0.85910695 0.68158202]]

 [[0.86400881 0.18501546]
  [0.39480339 0.18721189]]]


In [14]:
#using ndim property
print(a10.ndim)

3


In [15]:
#size property 
print(a10.size)

8


In [16]:
#datatype property
print(a10.dtype)

float64


In [17]:
#shape property
print(a10.shape)

(2, 2, 2)


In [18]:
#itemsize property
print(a10.itemsize)

8


In [19]:
#transpose property
print(a10.transpose)

<built-in method transpose of numpy.ndarray object at 0x782547540e70>
